### ISSUE TITLE
Snippet FileDownloadLink: Default template doesn't work in MODX 3

### ISSUE THREAD

**Issue by halftrainedharry** [Jako/FileDownloadR#1]
The default template

https://github.com/Jako/FileDownloadR/blob/d0f81e6608a725f8964b87a3304a62ba8e3c2187/core/components/filedownloadr/src/Snippets/FileDownloadLinkSnippet.php#L44

doesn't get parsed correctly, because `@CODE:` (with the colon at the end) is not in the list of valid types:

https://github.com/Jako/FileDownloadR/blob/d0f81e6608a725f8964b87a3304a62ba8e3c2187/core/components/filedownloadr/src/Helper/Parse.php#L43-L48

Also, the availability of _pdoTools_ is not detected correctly in MODX 3:

https://github.com/Jako/FileDownloadR/blob/d0f81e6608a725f8964b87a3304a62ba8e3c2187/core/components/filedownloadr/src/Helper/Parse.php#L90

---

Related topic in the MODX forum: https://community.modx.com/t/filedownloadr-3-0-0-snippet-filedownloadlink-isnt-working/6757

**Comment by Jako** [comment]
Thanks for posting the issue. It is fixed with 3.0.1.
