### ISSUE TITLE
USergroups dont seem to work

### ISSUE THREAD

**Issue by Lefthandmedia** [Jako/FileDownloadR#3]
Hi, i have a page with this tag on it 
```
[[!FileDownload? &mediaSourceId=`4` &groupByDirectory=`1` &userGroups=`1,2,3,4` ]]
```
This will give me a small login  form on the page (name, password) when i fill this in the form disappears and the message `You need to login to download files.` appears. But not a list of links.

I do login in as a member of usergroup 4. When i remove the `&userGroups=1,2,3,4` part the list does show up. So im not able to show this list of files only to a selected usergroup. Do i need to set something specific for these usergroups?

Using MODX 2.8.5

Any ideas?

RDG

**Comment by Jako** [comment]
You have to use user group names in the &userGroups property.

**Comment by Jako** [comment]
The properties description is updated in the docs: https://jako.github.io/FileDownloadR/usage/
