### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by travisbotello** [Jako/FileDownloadR#4]
I am trying to install/update to the newest version on 2.8.5 but it gets always stuck at this point:

![Screenshot 2023-09-22 at 10 00 01](https://github.com/Jako/FileDownloadR/assets/1157380/699b27a6-1fdb-42f5-97fc-400ed6eadc28)

**Comment by travisbotello** [comment]
Solved...for whatever reason my `fd_paths` had over 350k entries. Truncated the table and re-run installation fixed it.

**Comment by Jako** [comment]
If I remember right: The way the hash was calculated before version 3.0, a new entry in fd_paths was created on every display of the snippet.

**Comment by travisbotello** [comment]
> If I remember right: The way the hash was calculated before version 3.0, a new entry in fd_paths was created on every display of the snippet.

Crazy, that explains why. My website has around 80k files to download. 😄

**Comment by Jako** [comment]
The tables on the develop machine were filled without any download.

**Comment by Deesen** [comment]
I had exact the same issue today on MODX 2.8.6. Truncating table "fd_paths" immediately solved the problem, while mine only had 6k entries. But still caused the installation/update-process (from 2.0.0) to fail with error "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted". Strange...

**Comment by Jako** [comment]
This should be fixed with 3.1.2 by changing $modx->getCollection to $modx->getIterator.
