### ISSUE TITLE
No code snippet examples

### ISSUE THREAD

**Issue by vrdriver** [Jako/FileDownloadR#7]
Can you please add some examples to the documentation of suggested use cases for this?

Adding the following to a modx page does nothing:

```
[[FileDownload 
&getDir=`assets` 
&browseDirectories=`'1`]]
```

Can you suggest anything?

I'm using ModX 3 with the default starter template, and so even trying other options, I get nothing.

The rendered HTML:
```
<div class="container">
    <section>
        <h1>test</h1>
         test content 
         
    </section>
```

The TEXTAREA for the content:

```
 test content

 [[!FileDownload?
                &getDir=`assets/vendors`
                &tplFile=`tplDownloadForm`
                &downloadByOther=`0`
                &extShown=`jpg`
                &dateFormat=`d.m.Y`
                ]]
```

Cheers,
Steve

**Comment by vrdriver** [comment]
Struggling with ModX. It used to be amazing 10 years ago. Seems nothing works any more. A real shame.

**Comment by Jako** [comment]
In your first example there is a missing question mark in the snippet call and there is a ' in the browseDirectories property. It should be:

```
[[FileDownload?
&getDir=`assets`
&browseDirectories=`1`]]
```

The missing question mark causes the empty result of the snippet.

**Comment by Jako** [comment]
The second example shows a result if the folder and some jpg files exist in the assets/vendors folder on my local development machine using your snippet calls. So there has to be some different issue in your installation.

**Comment by vrdriver** [comment]
Thanks for investigating this further for me. I assume you're on modx3? I'll go back and have a look more.

**Comment by Jako** [comment]
I checked that on the latest 2.x and 3.x MODX versions.

Are there any issues in the MODX error log?

**Comment by vrdriver** [comment]
Well, I don't know why it didn't work for me originally, but your last example worked a treat! 

Also, while testing this out further, I've found something interesting (which I really like - as it means I won't have to change things on our server), and that is that the 'encrypted' URLs created by your plugin actually bypass the apache .htacess username/password mechanism. 

So, that's actually a plus for me, because my new test download page is authenticated by a different method, and I can still have users continue to use the rest of the site without changing their workflow.
 
I must have just had the whole thing misconfigured in my initial implementation.

Just for you info, this is the install log I got.
Running on a MAMP localhost, with PHP 8.2.0

Console running...
Attempting to install package with signature: filedownloadr-3.1.3-pl
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Installing/updating dependencies, this may take some time...
PHP deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Using ${var} in strings is deprecated, use {$var} instead
PHP deprecated: Using ${var} in strings is deprecated, use {$var} instead
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\DepthRangeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/installed.json): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/installed.php): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/InstalledVersions.php): Failed to open stream: No such file or directory
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP deprecated: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/autoload_namespaces.php): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/autoload_psr4.php): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/autoload_classmap.php): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/autoload_static.php): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/platform_check.php): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/autoload.php): Failed to open stream: No such file or directory
PHP warning: file_get_contents(/my_temp_site/core/components/filedownloadr/vendor/composer/autoload_real.php): Failed to open stream: No such file or directory
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 2 installs, 0 updates, 0 removals
- Downloading ip2location/ipinfodb-php (1.0.0)
- Downloading ralouphie/mimey (2.1.0)
- Installing ip2location/ipinfodb-php (1.0.0): Extracting archive
- Installing ralouphie/mimey (2.1.0): Extracting archive
Generating optimized autoload files
Altering table: fdCount
- Updating columns
-- altered column: id
-- altered column: ctx
-- altered column: filename
-- altered column: count
-- altered column: hash
- Updating indexes
Altering table: fdDownloads
- Updating columns
-- altered column: id
-- altered column: path_id
-- altered column: ip
-- altered column: referer
-- altered column: country
-- altered column: region
-- altered column: city
-- altered column: zip
-- altered column: geolocation
-- altered column: user
-- altered column: timestamp
- Updating indexes
-- removed index: path
-- removed index: user
-- added index: path
-- added index: user
Altering table: fdPaths
- Updating columns
-- altered column: id
-- altered column: ctx
-- altered column: media_source_id
-- altered column: filename
-- altered column: hash
- Updating indexes
System event "OnFileDownloadLoad" was created.
System event "OnFileDownloadBeforeDirOpen" was created.
System event "OnFileDownloadAfterDirOpen" was created.
System event "OnFileDownloadBeforeFileDownload" was created.
System event "OnFileDownloadAfterFileDownload" was created.
System event "OnFileDownloadBeforeFileUpload" was created.
System event "OnFileDownloadAfterFileUpload" was created.
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
PHP deprecated: Creation of dynamic property MODX\Revolution\modConnectorResponse::$response is deprecated
Successfully installed package filedownloadr-3.1.3-pl

**Comment by Jako** [comment]
I'm glad I could help you.

The encrypted links should not bypass a .htaccess security. I am not sure what happens there. Maybe the browser remembers the username/password in between.

The warnings during the install are mostly created by MODX itself. This will be solved in the next MODX version.

**Comment by vrdriver** [comment]
I just tested it again, and it still seems to be bypassing the .htaccess still. I'd call it a feature as it's something I prefer. Saves on entering a password twice.
