### ISSUE TITLE
url gets cut off

### ISSUE THREAD

**Issue by tebulrich** [Jako/FileDownloadR#9]
We always have to do something like this: ```[[+fd.url:replace=`ets/==assets/`:toPlaceholder=`img`]]``` because it removes a part of the url. This problem is in every project we use it and the part that we need to replace is different from project to project.

**Comment by Jako** [comment]
Please post your snippet call here.

**Comment by Jako** [comment]
I am closing this issue due to lack of response. Please reopen it if the problem still exists and add more information about your setup.
